apiVersion: batch/v1
kind: Job
metadata:
  name: nirmata-test
spec:
  template:
    spec:
      containers:
      - name: nirmata-test
        image: ssilbory/nirmata-test:1
        command: ["/scripts/k8_test/nirmata_test.sh",  "--nirmata" ]
        volumeMounts:
          - name: nirmata-test-script
            mountPath: /scripts/k8_test
          - name: nirmata-config-file
            mountPath: /scripts/nirmata-config-file
        env:
        - name: KUBECONFIG
          value: "/scripts/nirmata-config-file/config"
      volumes:
          - name: nirmata-test-script
            configMap:
                name: nirmata-test-script
                defaultMode: 0555
          - name: nirmata-config-file
            secret:
                secretName: nirmata-config-file
      restartPolicy: Never
  backoffLimit: 1
